version: "3.5"

services:
    frontend:
        image: mocap/frontend
        container_name: mocap-frontend
        build:
            context: ./
            target: production
            dockerfile: Dockerfile
        env_file:
            - .env.production
            - .env.production.local
        ports:
            - "3000:3000"
        networks:
            - mocap
        restart: always

networks:
    mocap:
        external: true
